import 'dart:convert';

import 'package:flutter/cupertino.dart';

import '../models/cart_item.dart';
import '../models/order_item.dart';
import 'package:http/http.dart' as http;

class Orders with ChangeNotifier {
  List<OrderItem> _orders = [];

  List<OrderItem> get orders {
    return [..._orders];
  }

  void addOrder(List<CartItem> cartProducts, double total) async {
    final String url = 'https://udemy-shop-app-course.firebaseio.com/orders.json';

    final DateTime timeStamp = DateTime.now();
    //Post to add new order
    final response = await http.post(url,
        body: json.encode({
          'amount': total,
          'dateTime': timeStamp.toIso8601String(),
          'product': cartProducts.map((cartProduct) => {
                    'id': cartProduct.id,
                    'title': cartProduct.title,
                    'quantity': cartProduct.quantity,
                    'price': cartProduct.price,
                  })
              .toList()
        }));

    _orders.insert(
        0,
        OrderItem(
            //get firebase autogenerated id
            id: json.decode(response.body)['name'],
            amount: total,
            timeOfOrder: DateTime.now(),
            products: cartProducts));

    notifyListeners();
  }
}
